config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
  end
  resources :tickets
  resources :attachments, only: [:show, :new]
  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      collection do
        get :search
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  namespace :admin do
    root "application#index"
    resources :projects, only: [:new, :create, :destroy]

    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end

    resources :users do
      member do
        patch :archive
      end
    end

  end

  resources :posts
  namespace :admin do
    resources :books
  end
  resources :products do
    get :who_bought, on: :member
  end
  resources :test_adminltes
  resources :brands
  resources :categories
  resources :sub_categories
  get 'registrations/update'

  resources :users, only: [:index]

  devise_for :users
  delete 'user' => 'devise/registrations#destroy'

  get 'home/index'

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    resources :stores
    get 'store/index'
  end

  root 'projects#index'

end

app/models/store.rb
class Store < ActiveRecord::Base
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  include CurrentCart
  skip_after_action :verify_authorized, :verify_policy_scoped
  before_action :set_cart
  before_action :set_store, only: [:show, :edit, :update, :destroy]


  # GET /stores
  # GET /stores.json
  def index
    if params[:set_locale]
      flash[:notice] = "We've just completed multi language for -Cart Multi Language- module. Please take a look at -Cart- to observe the changes "
      redirect_to stores_url(locale: params[:set_locale])
    else
      @products = Product.order(:title)
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.fetch(:store, {})
    end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<section class="content invoice">
  <div class="row">
    <div class="col-md-10">
      <%= form_for(@store, :html => { :role => "form" }) do |f| %>
        <% if @store.errors.any? %>
          <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <h4><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h4>

            <ul>
            <% @store.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

      <div class="form-group">
        <%= f.submit :class => "btn btn-flat bg-olive" %>
      </div>
    <% end %>
    </div>
  </div>
</section> 

app/views/stores/edit.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "Stores", stores_path %></li>
        <li class="active">Edit</li>
      </ol>
    </h1>
  </section>
<% end %>

<%= render 'form' %>

app/views/stores/index.html.erb
<% content_for :content_header do %>
    <section class="content-header">
      <h1><%= translate("listing") %>
        <small><%= translate("product") %></small>
      </h1>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> <%= translate("home") %></a></li>
        <li class="active"><%= translate("product") %></li>
      </ol>
    </section>
<% end %>

<section class="content col-md-8">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">

          </div>
        </div>
        <div class="box-body table-responsive">
          <table class="table table-hover">
            <thead>
            <tr>
              <th><%= translate("title")%></th>
              <th><%= translate("description")%></th>
              <th><%= translate("image")%></th>
              <th><%= translate("price")%></th>
              <th><%= translate("action")%></th>
            </tr>
            </thead>
            <tbody>
            <% @products = Product.order(:title) %>
            <% #cache ['stores', Product.latest] do %>
                <%= content_tag_for(:tr, @products) do |product| %>

                    <% #cache ['entry', product] do %>
                        <div class="entry">
                          <td width="15%"><%= product.title %></td>
                          <td width="30%"><%= truncate(strip_tags(product.description), length: 80)%></td>
                          <td><%= image_tag(product.image_url, class: 'list_image', width: "100px") %></td>
                          <td><%= number_to_currency product.price  %></td>
                          <td>
                            <%= button_to translate('.add_to_cart'), line_items_path(product_id: product),
                                          remote: true , class: "c-add-to-cart"%>
                          </td>
                        </div>
                    <% #end %>
                <% end %>
            <% #end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="c-pop-cart col-md-4">
  <div class="user-body">
    <div class="text-center">
      <% if session[:cart_id] && @cart = Cart.find(session[:cart_id]) %>
          <%= render @cart %>
      <% end %>
    </div>
  </div>
</div>

app/views/stores/new.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>New <small>Store</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "Store", stores_path %></li>
      <li class="active">New</li>
    </ol>
  </section>
<% end %>

<%= render 'form' %>

app/views/stores/show.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Show <small>store</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "Stores", stores_path %></li>
      <li class="active">Show</li>
    </ol>
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to edit_store_path(@store), :class => 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
            <% end %>          
          </div>
        </div>
        <div class="box-body">
          <dl class="dl-horizontal">
          </dl>
        </div>
      </div>
    </div>
  </div>
</section>