config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
  end
  resources :tickets
  resources :attachments, only: [:show, :new]
  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      collection do
        get :search
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  namespace :admin do
    root "application#index"
    resources :projects, only: [:new, :create, :destroy]

    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end

    resources :users do
      member do
        patch :archive
      end
    end

  end

  resources :posts
  namespace :admin do
    resources :books
  end
  resources :products do
    get :who_bought, on: :member
  end
  resources :test_adminltes
  resources :brands
  resources :categories
  resources :sub_categories
  get 'registrations/update'

  resources :users, only: [:index]

  devise_for :users
  delete 'user' => 'devise/registrations#destroy'

  get 'home/index'

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    resources :stores
    get 'store/index'
  end

  root 'projects#index'

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  validates :name, presence: true
  validates :category_id, presence: true
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  skip_after_action :verify_authorized, :verify_policy_scoped
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
    @sub_category = SubCategory.find(params[:id])
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_params
      params.require(:sub_category).permit(:name, :category_id, :published)
    end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<section class="content invoice">
  <div class="row">
    <div class="col-md-10">
      <%= form_for(@sub_category, :html => { :role => "form" }) do |f| %>
        <% if @sub_category.errors.any? %>
          <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <h4><%= pluralize(@sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h4>

            <ul>
            <% @sub_category.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :category_id %>
        <% @categories = Category.all %>
        <%= select_tag "sub_category[category_id]",
                       options_from_collection_for_select(@categories, "id", "name", @sub_category.category_id),
                       include_blank: "Please choose a Category", class: "form-control"
        %>

      </div>
      <div class="form-group">
        <%= f.label :published %>
        <%= f.check_box :published, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit :class => "btn btn-flat bg-olive" %>
      </div>
    <% end %>
    </div>
  </div>
</section> 

app/views/sub_categories/edit.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "Sub categories", sub_categories_path %></li>
        <li class="active">Edit</li>
      </ol>
    </h1>
  </section>
<% end %>

<%= render 'form' %>

app/views/sub_categories/index.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Listing <small>Subcategories</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Subcategories</li>
    </ol>    
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to new_sub_category_path(@sub_category), :class => 'btn btn-flat bg-olive' do %>
              <span class="glyphicon glyphicon-plus"></span>
              New Sub category
            <% end %>          
          </div>
        </div>
        <div class="box-body table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
              <th>Name</th>
              <th>Category</th>
              <th>Published</th>
                            <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <%= content_tag_for(:tr, @sub_categories.includes(:category)) do |sub_category| %>
              <td><%= sub_category.name %></td>
              <td><%= sub_category.category.nil? ? "" : sub_category.category.name %></td>
                <% if sub_category.published == true  %>
                    <td><span class="label label-success">Published</span></td>
                <% else %>
                    <td><span class="label label-warning">Unpublished</span></td>
                <% end %>
                <td>
                  <%= link_to  sub_category, class: "btn btn-primary btn-flat" do %>
                      <i class="glyphicon glyphicon-list"></i>
                  <% end %>
                  <%= link_to edit_sub_category_path(sub_category), class: "btn btn-default btn-flat" do %>
                      <i class="glyphicon glyphicon-pencil"></i>
                  <% end %>
                  <%= link_to sub_category, class: "btn btn-danger btn-flat", method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="glyphicon glyphicon-trash"></i>
                  <% end %>
                </td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/sub_categories/new.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>New <small>sub_category</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "sub_categories", sub_categories_path %></li>
      <li class="active">New</li>
    </ol>
  </section>
<% end %>

<%= render 'form' %>

app/views/sub_categories/show.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Show <small>sub_category</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "Sub_categories", sub_categories_path %></li>
      <li class="active">Show</li>
    </ol>
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to edit_sub_category_path(@sub_category), :class => 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
            <% end %>          
          </div>
        </div>
        <div class="box-body">
          <dl class="dl-horizontal">
            <dt>Name:</dt>
            <dd><%= @sub_category.name %></dd>

            <dt>Category:</dt>
            <dd><%= @sub_category.category_id %></dd>

            <dt>Published:</dt>
            <dd><%= @sub_category.published %></dd>

          </dl>
        </div>
      </div>
    </div>
  </div>
</section>