config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
  end
  resources :tickets
  resources :attachments, only: [:show, :new]
  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      collection do
        get :search
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  namespace :admin do
    root "application#index"
    resources :projects, only: [:new, :create, :destroy]

    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end

    resources :users do
      member do
        patch :archive
      end
    end

  end

  resources :posts
  namespace :admin do
    resources :books
  end
  resources :products do
    get :who_bought, on: :member
  end
  resources :test_adminltes
  resources :brands
  resources :categories
  resources :sub_categories
  get 'registrations/update'

  resources :users, only: [:index]

  devise_for :users
  delete 'user' => 'devise/registrations#destroy'

  get 'home/index'

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    resources :stores
    get 'store/index'
  end

  root 'projects#index'

end

app/models/admin/state.rb
class Admin::State < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
  def to_s
    name
  end

  def make_default!
    State.update_all(default: false)
    update!(default: true)
  end

  def self.default
    find_by(default: true)
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::ApplicationController

  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /admin/states
  # GET /admin/states.json
  def index
    @states = State.all
  end

  # GET /admin/states/1
  # GET /admin/states/1.json
  def show
  end

  # GET /admin/states/new
  def new
    @state = State.new
  end


  def create
    @state = State.new(state_params)
    if @state.save
      flash[:notice] = "State has been created."
      redirect_to admin_states_path
    else
      flash.now[:alert] = "State has not been created."
      render "new"
    end
  end

  def make_default
    @state = State.find(params[:id])
    @state.make_default!
    flash[:notice] = "'#{@state.name}' is now the default state."
    redirect_to admin_states_path
  end

  private

  def state_params
    params.require(:state).permit(:name, :color)
  end

  def set_user
    @state = State.find(params[:id])
  end

end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<section class="content invoice">
  <div class="row">
    <div class="col-md-10">
      <%= simple_form_for([:admin, @state], :html => {:role => "form"}) do |f| %>
          <% if @state.errors.any? %>
              <div class="alert alert-danger alert-dismissable" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                <h4><%= pluralize(@state.errors.count, "error") %> prohibited this admin_state from being saved:</h4>

                <ul>
                  <% @state.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <%= f.input :name, label: "Name", input_html: {class: "form-control"}, wrapper_html: {class: "form-group"} %>
          <div class="form-group">
            <%= f.label :color, style: "width: 100%;margin-bottom :8px;"%>
            <%= f.color_field :color %>
          </div>
          <%= f.submit :class => "form-group btn btn-flat bg-olive" %>
      <% end %>
    </div>
  </div>
</section> 

app/views/admin/states/edit.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><%= link_to "Admin States", admin_states_path %></li>
        <li class="active">Edit</li>
      </ol>
    </h1>
  </section>
<% end %>

<%= render 'form' %>

app/views/admin/states/index.html.erb
<% content_for :content_header do %>
    <section class="content-header">
      <h1>Listing
        <small>State</small>
      </h1>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">State</li>
      </ol>
    </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to new_admin_state_path(@admin_state), :class => 'btn btn-flat bg-olive' do %>
                <span class="glyphicon glyphicon-plus"></span>
                New State
            <% end %>
          </div>
        </div>
        <div class="box-body table-responsive">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Default</th>
              <th>Color</th>
            </tr>
            </thead>
            <tbody>
            <%= content_tag_for(:tr, @states) do |admin_state| %>
                <td><%= admin_state.id %></td>
                <td><%= admin_state.name %></td>

                <td>
                  <% if admin_state.default? %>
                      (Default)
                  <% else %>
                      <%= link_to "Make Default", make_default_admin_state_path(admin_state) %>
                  <% end %>
                </td>
                <td>
                  <span class="label" style='padding: 8px;background: <%= admin_state.color %> '>
                  <%= admin_state.color %></span>
                </td>


            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/states/new.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>New <small>State</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "State", admin_states_path %></li>
      <li class="active">New</li>
    </ol>
  </section>
<% end %>

<%= render 'form' %>

app/views/admin/states/show.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Show <small>admin_state</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "Admin_states", admin_states_path %></li>
      <li class="active">Show</li>
    </ol>
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to edit_admin_state_path(@admin_state), :class => 'btn btn-flat bg-olive' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
            <% end %>          
          </div>
        </div>
        <div class="box-body">
          <dl class="dl-horizontal">
          </dl>
        </div>
      </div>
    </div>
  </div>
</section>